name: scvi_tools
dependencies:
  - python=3.8.*
  - numpy
  - pytest
  - scanpy
  - pytorch
  - matplotlib
  - pandas=1.2.5
  - numba
  - pytables
  - scikit-learn
  - seaborn
  - statsmodels
  - pytorch-lightning
  - rich
  - docrep
  - torchmetrics
  - importlib_metadata
  - scvi-tools
  - leidenalg